### ISSUE TITLE
The death

### ISSUE THREAD

**Issue by nikita-volkov** [philopon/best-haskell#3]
It's very sad. I found this service to be quite useful. Is anything getting done to resurrect it? Can the community do anything?

**Comment by philopon** [comment]
Sorry for the late reply. I'm glad you like best-haskell:smile:

This project depends on `/packages/downloads` hackage-api, but it was closed.
I didn't know, but it might be internal-api because It provide very large csv(~100MB).

best-haskell revive when public api to get download count provided in future.

So, PR/Issue to [haskell/hackage-server](https://github.com/haskell/hackage-server) may resurrect best-haskell.

Thanks.
